### ISSUE TITLE
Note Detail API

### ISSUE THREAD

**Issue by jrhong95** [ThinLineIT/CtrlF_Backend#104]
1. 설명
    - 노트의 세부적인 정보를 전송
    - `note_id`를 받아 해당 id의 note 정보를 Return
    
2. URL
    - `GET /api/notes/{note_id}`

3. Return
    - 성공 : 200
    ```json
    {
        	"id": 1,
        	"title": "노트 제목",
        	"created_at": "생성일",
        	"is_approved": true,
        	"owners": [1, 2, ...],
    }
    ```
    - 실패
        - `note_id`가 유효하지 않은 경우 : 404

    ```json
    { 
            "message": "노트를 찾을 수 없습니다.",
    }
    ```

**Comment by TaeHyoungKwon** [comment]
@jrhong95 세화야 전체채널에 공지하고 작업 ㄱㄱ
