### ISSUE TITLE
닉네임 중복 확인 API

### ISSUE THREAD

**Issue by TaeHyoungKwon** [ThinLineIT/CtrlF_Backend#18]
## 문제
   * 회원가입시 같은 닉네임이 존재하는것을 막기위해 닉네임 중복 검사가 필요하다.
## 해결
   * client로부터 닉네임을 받았을 때, DB를 조회하여 닉네임 중복 검사를 한다. 
## 조건
   * 
## 절차
  1. Success 테스트 및 구현코드 작성
  2. Fail 테스트 및 구현코드 작성
  3. Swaager 등록 및 테스트
  4. 닉네임 중복 테스트
## 인수 테스트
  1. Success
      * Status Code 200을 리턴한다.
      * "사용 가능한 닉네임입니다." 라는 메시지를 리턴한다.
  2. Fail 
       1. 닉네임 중복  
             * Status Code 400을 리턴한다.
             * "이미 존재하는 닉네임입니다." 라는 메시지를 리턴한다.

**Comment by JinHoooooou** [comment]
## 문제
  * 사옹자의 닉네임이 중복됨
## 해결
  * Signup 과정에서 닉네임 중복을 미리 확인
## 조건
  * 데이터베이스 조회 필요
## 절차
  1. 입력한 닉네임이 데이터베이스에 존재하는지 확인
  2. 존재하지 않는다면 성공, 이미 존재하거나 유효값이 아니라면 실패  
## 인수 테스트
  * 성공
     *  사용할 닉네임을 입력 후 중복확인을 누르면, 사용가능하다는 메시지를 출력한다
  * 실패
     *  닉네임이 유효한 값이 아니라면(Empty String 등), 유효하지 않다는 메시지를 출력한다.
     *  이미 존재하는 닉네임이라면, 중복된 닉네임이라는 메시지를 출력한다.
