### ISSUE TITLE
이메일 중복 확인 API

### ISSUE THREAD

**Issue by TaeHyoungKwon** [ThinLineIT/CtrlF_Backend#19]
## 문제
* 회원가입 시 동일한 유저가 같은 계정으로 가입하는 것을 방지.
## 해결
* 회원가입 시 이메일 중복 검사.
## 조건
* 
## 절차
1. 인수테스트 기준 성공 테스트 구현, 테스트 통과 가능한 코드 작성.
2. 실패 테스트 구현, 테스트 통과 가능한 코드 작성.
3. swagger 등록, 테스트.
4. 이메일 중복 테스트.
## 인수 테스트
- 성공
    * status code : 200
    * message : 사용 가능한 이메일 입니다.
- 실패
    * 이미 존재하는 이메일일 경우
        * status code : 404
        * message : 이미 존재하는 이메일 입니다.
    * 이메일 형식이 유효하지 않을 경우
        * status code : 400
        * message : 이메일 형식이 유효하지 않습니다.

**Comment by jrhong95** [comment]
## 문제
* 회원가입 시 동일한 유저가 같은 계정으로 가입.
## 해결
* 회원가입 시 이메일 중복 검사.
## 조건
* DB 조회.
## 절차
1. 사용자에게 이메일 입력 받음.
2. Client에서 이메일 조회 API 실행.
2. Server로 전달 받은 이메일을 DB에서 조회.
3. 이미 존재하는 이메일인 경우 실패, 아닌 경우 성공.
## 인수 테스트
- 성공
    * 이메일 사용 가능하다는 메세지 전송.
- 실패
    1. 이메일 형식이 올바르지 않을 경우
        - 이메일 형식이 아니라는 메세지 전송.
    2. 이미 존재하는 이메일일 경우
        - 이미 존재하는 이메일이라는 메세지 전송
