### ISSUE TITLE
이메일 인증 메일 보내기 API

### ISSUE THREAD

**Issue by TaeHyoungKwon** [ThinLineIT/CtrlF_Backend#20]
## 문제
* 회원 가입을 위한 유효한 이메일 인지 인증 필요
## 해결
* django email 을 이용해서, 임의의 코드를 생성하여서 전달한다
## 조건
* code 테이블 생성 필요
## 절차
1. AuthCode 테이블을 만든다
2. 이메일 보내기 API를 호출 할 때, 임의의 8자리 코드를 생성한다(a-z,A-Z,0-9)
3. 생성된 코드를 AuthCode 테이블에 저장한다
4. send_mail로 code를 request body로 부터 받은 email로 보낸다 ( to: no_reply@ctrlf.com)
## 테스트
1. 인수 테스트
    1. 메일로 code가 전송되어야 한다
2. API 테스트
    1. 성공
        * 200을 리턴한다
    2. 실패
        * 400을 리턴한다(유효하지 않은 이메일 형식 입니다)

**Comment by wlsrn3684** [comment]
## 문제
* 회원가입을 하기 위해 이메일 인증이 필요
## 해결
* 서버에 요청을 통해 이메일을 발송해 인증을 할 수 있도록 한다
## 조건
* IMAP 설정
이메일 클라이언트에서 Gmail을 사용할 수 있게 IMAP 설정을 1단계로 설정한다.
* 보안수준 설정
보안 수준 설정을 통해 Gmail에서 자체 차단 없이 이메일을 발송할 수 있다.
* Django에서 SMTP 설정
Google SMTP를 이용하기 위해 프로젝트의 settings.py에 설정을 추가 합니다.
## 절차
1. 프론트에서 요청이 들어오면 입력받은 EMAIL로 인증 메일을 발송한다.
2. 
## 인수 테스트
- 성공
    * 사용자는 입력해놓은 EMAIL로 이메일 인증 메일을 받아야 한다.
- 실패
    1. 400
        - 이메일 발송 과정에서 에러가 발생하면 400를 리턴해야한다.
