### ISSUE TITLE
PUT 메소드

### ISSUE THREAD

**Issue by wlsrn3684** [ThinLineIT/CtrlF_Backend#3]
PUT 메소드로 수정을 할 때 수정할 필드만 리퀘스트 바디에 담아서 보내고 싶은데 안됨

**Comment by TaeHyoungKwon** [comment]
수정할 필드만 담아서 수정하려면 PATCH를 쓰면됨

FYI, https://papababo.tistory.com/entry/HTTP-METHOD-PUT-vs-PATCH-%EC%B0%A8%EC%9D%B4%EC%A0%90

**Comment by wlsrn3684** [comment]
넵 확인했습니다!
