### ISSUE TITLE
swagger PUT, DELETE 메소드 리퀘스트 바디 설정

### ISSUE THREAD

**Issue by wlsrn3684** [ThinLineIT/CtrlF_Backend#4]

**Comment by TaeHyoungKwon** [comment]
이건 PUT, DELETE 메소드 리퀘스트 바디 설정 하는 방법을 모르겠다라는 말인가??

**Comment by wlsrn3684** [comment]
넵 포스트랑 똑같이 하기에는 필요없는 필드들이 포함될 것 같아서 다른 방법이 있나 찾아봤는데 못 찾겠어서 혹시 시리얼라이저를 새로 만들어서 집어넣어줘야할까요?

**Comment by TaeHyoungKwon** [comment]
근데 현재 PUT으로 만들어둔 API는 동작하는 API가 맞는거야? feature 브랜치에 있는거

**Comment by wlsrn3684** [comment]
네네 모든 필드 값 채워주면 동작해요

**Comment by TaeHyoungKwon** [comment]
feature 브랜치에 커밋추가해서 올려두었으니 확인해보고 나머지도 비슷하게 작성하면될거같애
