### ISSUE TITLE
인증코드 검증 API

### ISSUE THREAD

**Issue by jrhong95** [ThinLineIT/CtrlF_Backend#94]
## 문제
* 실제 사용중인 이메일인지 확인해야 함.
## 해결
* 회원가입 시 전송한 인증코드가 일치하는지 확인.
## 조건
* 인증코드 발송이 선행되어야 함.
## 절차
1. 인수테스트 기준 성공 테스트 구현, 테스트 통과 가능한 코드 작성.
2. 실패 테스트 구현, 테스트 통과 가능한 코드 작성.
3. swagger 등록, 테스트.
4. 실제 이메일을 통한 테스트.
## 인수 테스트
- 성공
    * status code : 200
    * message : "유효한 인증코드 입니다."
- 실패
    * status code: 400
    * message : "인증코드가 올바르지 않습니다."

**Comment by TaeHyoungKwon** [comment]
![스크린샷 2021-08-07 오후 8 52 11](https://user-images.githubusercontent.com/18538418/128599200-f485caeb-6a22-49ac-989d-87d8f6d878c0.png)

위 인수테스트 결과에 대해서, QA 해보고 댓글로 결과 남겨주고 완료되면 Close 하면된다~

**Comment by jrhong95** [comment]
![image](https://user-images.githubusercontent.com/22022731/128638558-e5f95a6c-c1fd-4e75-9308-91be39ddf240.png)
