### ISSUE TITLE
Note List API

### ISSUE THREAD

**Issue by JinHoooooou** [ThinLineIT/CtrlF_Backend#97]
1. Note list API
    - Description
        - 생성된 노트 리스트를 리턴한다.
        - 승인/미승인 분류를 할 수 있다.
        - cursor based pagination
    - Parameter
        - cursor
            - 현재 커서를 기준으로 30개의 note list를 리턴한다.
    - Url

        `GET {BASE_URL}/api/notes`

    - Request

        `GET {BASE_URL}/api/notes?cursor=0`

    - Response
        - 200 OK

            ```json
            {
            	"next_cursor": 30,
            	"notes": [
            		{
            			"id": 1,
            			"title": "알고리즘",
            			"is_approved": true
            		},
            		{
            			"id": 2,
            			"title": "데이터구조",
            			"is_approved": false
            		},
            		{
            			"id": 3,
            			"title": "데이터베이스",
            			"is_approved": false
            		},
            		...
            	]
            }
            ```

**Comment by TaeHyoungKwon** [comment]
`Note Create API` 이건 이슈를 나눠서 작성해주셈~

**Comment by TaeHyoungKwon** [comment]
@JinHoooooou  note list 작업 시작하면 될 것 같다~
